quarkus:
  datasource:
    username: bob
    password: bob
    reactive:
      url: vertx-reactive:postgresql://localhost:6000/smartbarbo
  hibernate-orm:
    database:
      generation: drop-and-create
  ssl:
    certificate:
      key-store-file: smartbarbo.p12
      trust-store-file: sbotrust.p12
    client-auth: required
  insecure-requests: redirect
  http:
    auth:
      basic: true
