quarkus:
  datasource:
    username: bob
    password: bob
    jdbc:
      url: jdbc:postgresql://${db-host}:5432/smartbarbo
  oidc:
    auth-server-url: http://${keycloak-host}:8080/realms/sbo
    client-id: smartbar-backoffice
    application-type: hybrid
    token-state-manager:
      split-tokens: true
    roles:
      source: accesstoken
kafka:
  bootstrap:
    servers: bo-kafka:9092
mp:
  messaging:
    outgoing:
      masterdata-changed-channel:
        connector: smallrye-kafka
        topic: update-menu-events
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
