quarkus:
  http:
    port: 8088
  datasource:
    username: bob
    password: bob
    jdbc:
      url: jdbc:postgresql://localhost:5432/smartbarbo
  hibernate-orm:
    database:
      generation: drop-and-create
  oidc:
    auth-server-url: http://localhost:7070/realms/sbo
    client-id: smartbar-backoffice
    application-type: hybrid
    token-state-manager:
      split-tokens: true
    roles:
      source: accesstoken
kafka:
  bootstrap:
    servers: localhost:9092
rabbitmq-host: localhost
rabbitmq-port: 5672
mp:
  messaging:
    outgoing:
      masterdata-changed-channel:
        connector: smallrye-rabbitmq
        exchange:
          type: topic
          name: smartbar