quarkus:
  http:
    port: 8088
  hibernate-orm:
    database:
      generation: drop-and-create
  oidc:
    auth-server-url: http://localhost:7070/realms/sbo
    client-id: smartbar-backoffice
    application-type: hybrid
    token-state-manager:
      split-tokens: true
    roles:
      source: accesstoken
kafka:
  bootstrap:
    servers: localhost:9092
mp:
  messaging:
    outgoing:
      masterdata-changed-channel:
        connector: smallrye-kafka
    incoming:
      article-ordered-channel:
        connector: smallrye-kafka
        topic: orders-events
        group:
          id: backoffice-article-updater
      turnover-db-channel:
        connector: smallrye-kafka
        topic: orders-events
        group:
          id: backoffice-turnover-updater