quarkus:
  datasource:
    username: bob
    password: bob
    reactive:
      url: vertx-reactive:postgresql://localhost:5432/smartbarbo
  hibernate-orm:
    database:
      generation: drop-and-create
  http:
    auth:
      basic: true
    ssl:
      certificate:
        key-store-file: smartbarbo.p12
        trust-store-file: sbotrust.p12
      client-auth: required
    insecure-requests: redirect
